# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://diverseathonuva.com"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "Diverse-a-thon UVA"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Diverse-a-thon UVA | 27-29 October 2017"
  description: "DIVERSE-A-THON | UVA "
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Diverse-a-thon UVA"
  description: "DIVERSE-A-THON | UVA"
  date:        "October 27-29, 2017"
  location:    "Charlottesville, VA"

  trust_badge:
    year:   "2018"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        href: "https://diverseathonuva.typeform.com/to/bg9Zja"
      - text: "Sponsor"
        href: "mailto:tmp2bf@virginia.edu"

  about:
    description: >
     We define diversity as excellence expressing itself through the intersection of perspectives and lived experiences. Where do technology and diversity converge? How can we use technology to advance issues in diversity? What can YOU invent to answer these questions? Diverse-a-thon UVA seeks to take hackathons to a new level through an event filled with perspective-changing moments. From workshops and talks by the most prominent thought leaders in diversity, to participants filled to the brim with excellence and passion, we're excited to host you at The University of Virginia.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "GUEST SPEAKERS."
        description: >
          At the Diverse-a-thon, you can expect tech talks and workshops from UVA Professors, professionals, and thought leaders on a variety of topics. We will also have a very special guest who just might want to Save the World. 
      - image: "images/image2.png"
        title: "ROOM TO BUILD."
        description: >
          The event will be held in the Slaughter Recreation Center at UVA, with plenty of room to explore, learn, and collaborate. Its location on grounds will also allow you to experience the history and magic of a real UNESCO world heritage site. 
      - image: "images/image3.png"
        title: "GREAT PRIZES."
        description: >
          Let's not forget about the thousands of dollars in prizes up for grabs provided by our sponsors, partners, and us. We will have a wide array of categories and competitions, and a whole bunch of swag so nobody leaves empty handed. 

  # Frequently asked questions.
  #potential other questions- what activities, what can we expect, what is the center for diversity in engineering
  
  faq:
    - question: "What is a hackathon? I've never coded before, so is this an event for me?"
      answer: >
        [MLH](mlh.io) defines hackathon as 'invention marathon'. At the Diverse-athon, there will be guest lectures, food, prizes, mentors, and more! Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl). If you've got an idea and willingness to learn, this event is for you!
    - question: "What is different about this hackathon?"
      answer: 
        The Diverse-a-thon is focused on real-life real-time problem solving. Instead of inventing for inventing's sake, we want hackers to create something that will make the world a better place.
    - question: "Are you sure it's for beginners?"
      answer: >
        Yes!
    - question: "How many members can I have on my team?"
      answer: >
        You may have up to four members. If you'd like to work alone on a solo hack, you are also more than welcome to. 
    - question: "Will I fit in?"
      answer: >
        Yes! We anticipate that students from different schools, backgrounds, and skills, from beginners to experienced hackers will be attending. If you don't have a team in mind, there will be team building activities. 
    - question: "How much does it cost?"
      answer: >
        This event (including workshops, speakers, and food) will be free, courtesy of the Office for Diversity and Engagement and the Department of Computer Science at the University of Virginia. We do ask that you [pre-register](https://diverseathonuva.typeform.com/to/bg9Zja) as soon as possible so that we can provide enough food for attendees.
    - question: "Do I need to be a student to attend?"
      answer: >
        This event is open to college graduate and undergraduate students, of all ages and backgrounds. 
    - question: "Will travel costs be covered?"
      answer: > 
        We will be providing some buses across the east coast, and are hoping to be able to cover a portion of travel costs. Stay tuned for more updates. 
    - question: "What do I need to bring?"
      answer: >
        All you will need is willingness to learn, a laptop/charger, a sleeping bag, a pillow, and a few ideas! 
    - question: "Where is the event?"
      answer: >
        The event is being hosted in the Slaughter Recreation Center at the University of Virginia. Directions can be found [here](https://www.google.com/maps/place/Slaughter+Recreation+Center,+505+Edgemont+Rd,+Charlottesville,+VA+22903/@38.0348618,-78.5200301,17z/data=!3m1!4b1!4m5!3m4!1s0x89b38658533378ad:0x1f894558a05e15d2!8m2!3d38.0348685!4d-78.5178826). We will be providing rooms to sleep in, but we encourage you to bring a sleeping bag and pillow. The university will not be providing a place to stay Friday night, however, but there are many [places](https://www.tripadvisor.com/Hotels-g57592-Charlottesville_Virginia-Hotels.html) to stay in Charlottesville. 
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "How do I register?"
      answer: > 
        We are currently [accepting pre-registration forms](https://diverseathonuva.typeform.com/to/bg9Zja). We encourage you to apply as soon as possible. Once you've applied, stay tuned for more information. 

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
